# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 598196d41eaec0da8bb7b3dbca7ffc9a47b1cbcd3a988d0c6fc38f98d3f7870476a841f520db3af715b75a75486fb816028ee09e2d8288294cbacdc897265eec

test:
  secret_key_base: f9dbad4a5615393580d93051d322632e4b32af678fb14f15a5c6d42e2f2dce904845ac7573823f26fc879e004eae6d2bd57712dc71891c8d1b996efa7c24afc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
